<a href="https://colab.research.google.com/github/ManudiZeta/PyTorch_train/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/$0

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cpu


##Introduction to tensors

### Creating tensors



In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tenors back as Python int
scalar.item()

7

In [5]:
#vector (it has more than one number)

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim #it has dim = 1, since it is a raw

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0,1]

tensor(8)

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start full of random numbers and then adjust those random numbers to better represent the data. (they are the weight)

'Start with random numbers -> look at data -> update random numbers (ricorsive)

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4136, 0.0122, 0.5245, 0.4938],
        [0.2580, 0.4730, 0.6135, 0.5967],
        [0.8387, 0.8163, 0.7481, 0.1689]])

In [17]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones (Masks)

In [18]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device="cpu", #what device is your tensor on
                               requires_grad=False #whether or not to track gradients with this tensors operations
                               )
float_32_tensor


tensor([3., 6., 9.])

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [28]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (tensro attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [29]:
# Create a tensor
some_tensor = torch.rand([3,4], dtype = torch.float32)
some_tensor

tensor([[0.8117, 0.1796, 0.3821, 0.4206],
        [0.2925, 0.0937, 0.4666, 0.3105],
        [0.4075, 0.4113, 0.8465, 0.5282]])

In [30]:
# Find out detail about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8117, 0.1796, 0.3821, 0.4206],
        [0.2925, 0.0937, 0.4666, 0.3105],
        [0.4075, 0.4113, 0.8465, 0.5282]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)-> Fondamentali per fare la convoluzione con i filtri, ad esempio

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Create a tensor and mult 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [33]:
# Create a tensor and sub 10 to it
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Create a tensor and mult 10 to it (PyTorch method)
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication (Convolution)
Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication (scalar or dot product)
2. Matrix multiplication (cross product or
convolution)

There are two main rules that performing matrix multiplication need to satisfy:

1. The **inner dimensions** must match:

*(3,2) @ (3,2) won't work
*(2,3) @ (3,2) will work.
*(3,2) @ (2,3) will work.

2. The resulting matrix has the shape of the **outer dimensions**
(2,3) @ (3,2) = (2,2)

In [35]:
a = torch.rand(2,3)
print(f"a =  {a} \n")
b = torch.rand(3,2)
print(f"b =  {b}")

print(f" a @ b = {a @ b}")


a =  tensor([[0.5202, 0.4134, 0.1522],
        [0.2704, 0.6904, 0.5233]]) 

b =  tensor([[0.3143, 0.1785],
        [0.9888, 0.5315],
        [0.6600, 0.5317]])
 a @ b = tensor([[0.6727, 0.3935],
        [1.1130, 0.6935]])


In [36]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor) # fa (tensor)^T * (tensor)

tensor(14)

In [38]:
a = torch.tensor ([[1,2,3],[4,5,6]])
b = torch.tensor ([[7,8],[9,10],[11,12]])
torch.mm(a,b)


tensor([[ 58,  64],
        [139, 154]])

In [39]:
%%time
value = 0

for i in range (len(tensor)):
  value += tensor [i] * tensor [i]

value

CPU times: user 1.3 ms, sys: 192 µs, total: 1.49 ms
Wall time: 4.12 ms


tensor(14)

In [40]:
%%time
torch.matmul(tensor,tensor) # <-- questo è molto più veloce del for loop

CPU times: user 374 µs, sys: 0 ns, total: 374 µs
Wall time: 314 µs


tensor(14)

### One of the most common errors in deep learning: *shape errors*

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,5],
                        [5,6]])

tensor_B = torch.tensor ([[7,10],
                          [8,11],
                          [9,12]])

#torch.mm(tensor_A,tensor_B) torch.mm is the same as torch.matumul (it is an alias for writing less code)
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** swithces the axes or dimensions of a given tensor

In [42]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [43]:
# Therefore, with the transposed tensor, I can perfrom the matrix multiplication
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [108, 147]])

In [44]:
torch.matmul(tensor_A.T,tensor_B).shape

torch.Size([2, 2])

### Finding the min, max, mean, sum etc... (tensor aggregation)

In [52]:
# Create a tensor
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
# Find the min:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [54]:
# Find the max:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [55]:
# Find the mean <-- non possiamo usare dei long tensor (64)...torch.mean() require a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [57]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Find the POSITION in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [60]:
# Find the POSITION in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [61]:
x[9]

tensor(91)