<a href="https://colab.research.google.com/github/ManudiZeta/PyTorch_train/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/$0

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cu128


##Introduction to tensors

### Creating tensors



In [2]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tenors back as Python int
scalar.item()

7

In [5]:
#vector (it has more than one number)

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim #it has dim = 1, since it is a raw

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0,1]

tensor(8)

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start full of random numbers and then adjust those random numbers to better represent the data. (they are the weight)

'Start with random numbers -> look at data -> update random numbers (ricorsive)

In [16]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2865, 0.6357, 0.1068, 0.4552],
        [0.0705, 0.8276, 0.2682, 0.6061],
        [0.0290, 0.6592, 0.9412, 0.4473]])

In [17]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones (Masks)

In [18]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device="cpu", #what device is your tensor on
                               requires_grad=False #whether or not to track gradients with this tensors operations
                               )
float_32_tensor


tensor([3., 6., 9.])

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [28]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (tensro attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [29]:
# Create a tensor
some_tensor = torch.rand([3,4], dtype = torch.float32)
some_tensor

tensor([[8.2596e-01, 3.8948e-01, 5.9600e-01, 3.5767e-01],
        [4.2337e-01, 6.1184e-01, 5.4163e-04, 7.0222e-01],
        [5.2676e-01, 1.2628e-02, 8.9431e-01, 2.0269e-01]])

In [30]:
# Find out detail about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[8.2596e-01, 3.8948e-01, 5.9600e-01, 3.5767e-01],
        [4.2337e-01, 6.1184e-01, 5.4163e-04, 7.0222e-01],
        [5.2676e-01, 1.2628e-02, 8.9431e-01, 2.0269e-01]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)-> Fondamentali per fare la convoluzione con i filtri, ad esempio

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [31]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Create a tensor and mult 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [33]:
# Create a tensor and sub 10 to it
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [34]:
# Create a tensor and mult 10 to it (PyTorch method)
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication (Convolution)
Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication (scalar or dot product)
2. Matrix multiplication (cross product or
convolution)

There are two main rules that performing matrix multiplication need to satisfy:

1. The **inner dimensions** must match:

*(3,2) @ (3,2) won't work
*(2,3) @ (3,2) will work.
*(3,2) @ (2,3) will work.

2. The resulting matrix has the shape of the **outer dimensions**
(2,3) @ (3,2) = (2,2)

In [35]:
a = torch.rand(2,3)
print(f"a =  {a} \n")
b = torch.rand(3,2)
print(f"b =  {b}")

print(f" a @ b = {a @ b}")


a =  tensor([[0.5487, 0.2459, 0.1971],
        [0.3166, 0.7206, 0.1242]]) 

b =  tensor([[0.7490, 0.1982],
        [0.9138, 0.5212],
        [0.7793, 0.4961]])
 a @ b = tensor([[0.7893, 0.3347],
        [0.9925, 0.5000]])


In [36]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor) # fa (tensor)^T * (tensor)

tensor(14)

In [38]:
a = torch.tensor ([[1,2,3],[4,5,6]])
b = torch.tensor ([[7,8],[9,10],[11,12]])
torch.mm(a,b)


tensor([[ 58,  64],
        [139, 154]])

In [39]:
%%time
value = 0

for i in range (len(tensor)):
  value += tensor [i] * tensor [i]

value

CPU times: user 1.21 ms, sys: 31 µs, total: 1.25 ms
Wall time: 3 ms


tensor(14)

In [40]:
%%time
torch.matmul(tensor,tensor) # <-- questo è molto più veloce del for loop

CPU times: user 415 µs, sys: 0 ns, total: 415 µs
Wall time: 1.57 ms


tensor(14)

### One of the most common errors in deep learning: *shape errors*

In [41]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,5],
                        [5,6]])

tensor_B = torch.tensor ([[7,10],
                          [8,11],
                          [9,12]])

#torch.mm(tensor_A,tensor_B) torch.mm is the same as torch.matumul (it is an alias for writing less code)
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**

A **transpose** swithces the axes or dimensions of a given tensor

In [42]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [43]:
# Therefore, with the transposed tensor, I can perfrom the matrix multiplication
torch.matmul(tensor_A.T,tensor_B)

tensor([[ 76, 103],
        [108, 147]])

In [44]:
torch.matmul(tensor_A.T,tensor_B).shape

torch.Size([2, 2])

### Finding the min, max, mean, sum etc... (tensor aggregation)

In [45]:
# Create a tensor
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [46]:
# Find the min:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [47]:
# Find the max:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [48]:
# Find the mean <-- non possiamo usare dei long tensor (64)...torch.mean() require a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [49]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [50]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [51]:
# Find the POSITION in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [52]:
# Find the POSITION in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [53]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensors to a defined shape
* View - return a view of an input tensor of a certain shape, but keep the same memory as the original tensor
* Stacking - combine mulitple tensors on top of each other (vstack - vertical) or side by side (hstack - horizontal)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze  - add all 1 dimensions to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [54]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [55]:
# Reshape - add an extra dimension <--- aumenta di una dimensione (aggiunge una [])
x_reshaped = x.reshape(1,9) # Deve essere multiplo!
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
# Change the view
z = x.view(1,9) # it's quite similar to shape...z is a kind of copy of x
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [57]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:,0] = 5 # Cambio tutte gli elementi della prima colonna in 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim = 1) # <--- Li incatasto verticalmente
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [59]:
# Squeeze and unsqueeze

# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}\n")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [60]:
# torch.unsqueeze() - add a single dimensions to a target tensor at specific dimension
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}\n")

# Add an extra dimensions with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [61]:
# torch.permute - rearranges the dimensions of a target tensor in a spcified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels (RGB)]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # Shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # Mi switcha l'ordine delle features


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [62]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
# Let's index on the middle bracket (dim = 1)
x[0][0] # Posso anche scrivere x [0,0]

tensor([1, 2, 3])

In [65]:
# Let's index on the most inner bracket
x[0][2][2]

tensor(9)

In [66]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [67]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [68]:
# Get all values of 0th but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [69]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [70]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [71]:
# Index on x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library. Becuase of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()



In [72]:
# Numpy array to tensor
import torch
import numpy as np


array = np.arange(1.,8)
tensor = torch.from_numpy(array) #WARNING: when converting from numpy -> pytorch, PyTorch reflects numpy's default datatype of float64 unless specified otherwise
#tensor = torch.from_numpy(array).type(torch.float32)

array, tensor #abbiamo un float64 come tipo del tensor, perché lo eredita dall'array NumPy. Questo non è il tipo base del tensor, che è float32. Dobbiamo cambiarlo

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
torch.arange(1.,8.).dtype

torch.float32

In [74]:
# Chane the value of array, what will this do to tensor? It doesn't affect the tensor object

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [75]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # This will has the tensor datatype (float32)...keep in mind
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [76]:
# Change the tensor, what happens to numoy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better rapresentation of the data -> again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially, what the random seed does is "flavour" the randomness.

In [77]:
torch.rand(3,3) # questo crea un numero diverso sempre...ma se volessi riproducibilità?

tensor([[0.0982, 0.0807, 0.9240],
        [0.5647, 0.6548, 0.1566],
        [0.2150, 0.4755, 0.8813]])

In [78]:
import torch
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B) # Mi torna se due oggetti sono uguali o diversi (= è True ------ ≠ è False)

tensor([[0.3744, 0.3053, 0.2546, 0.4336],
        [0.3830, 0.2251, 0.5134, 0.3494],
        [0.9561, 0.9671, 0.2530, 0.7842]])
tensor([[0.5387, 0.1265, 0.1657, 0.9624],
        [0.4660, 0.1495, 0.2670, 0.9836],
        [0.0880, 0.6523, 0.3900, 0.7221]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [79]:
# Let's make some random but reproducible tensors --> uso torch.manual_seed(Random_seed)
import torch

# Set the random seed <--- è come quando setto il seed del TRandom. Il concetto è proprio identico
Random_seed = 42
torch.manual_seed(Random_seed)
random_tensor_C = torch.rand(3,4)

#torch.manual_seed(Random_seed) #<-- Questo riazzera la sequenza pseudocasuale
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google COlab for a free GPU (options to upgrade as well)
2. USe your own GPU - takes a little bit of setup and requires the investement of purchasing a GPU (there's a lot of options)
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2 and 3, PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentations

In [80]:
!nvidia-smi

Fri May 22 07:46:25 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU acces with PyTorch

In [81]:
# Check forGPU acces with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch, since it is capable of running compute on the GPU for CPU,it's best practice to setup device agnostic code.

e.g. run on GPU if available, else default CPU

In [82]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [83]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want a tensors/models on the GPU is because using a GPU results in a faster computation




In [86]:
# Create a tensor (default on the CPU)
tensor = torch.tensor ([1,2,3],device = "cpu")

# Tensor not on GPU
print (tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [87]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [89]:
# If tensor is on GPU, can't transform it to NumPy (NumPy vuole cose sulla CPU)
#tensor_on_gpu.numpy()


#To fix GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])