<a href="https://colab.research.google.com/github/ManudiZeta/PyTorch_train/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/$0

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.10.0+cpu


##Introduction to tensors

### Creating tensors



In [3]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tenors back as Python int
scalar.item()

7

In [6]:
#vector (it has more than one number)

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim #it has dim = 1, since it is a raw

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0,1]

tensor(8)

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

Why random tensors?
Random tensors are important because the way many neural networks learn is that they start full of random numbers and then adjust those random numbers to better represent the data. (they are the weight)

'Start with random numbers -> look at data -> update random numbers (ricorsive)

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7016, 0.6223, 0.8751, 0.1617],
        [0.9936, 0.5464, 0.1840, 0.0455],
        [0.3708, 0.8426, 0.7961, 0.3475]])

In [18]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones (Masks)

In [19]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
zeros.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [24]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors-like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor
                               device="cpu", #what device is your tensor on
                               requires_grad=False #whether or not to track gradients with this tensors operations
                               )
float_32_tensor


tensor([3., 6., 9.])

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [32]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from Tensors (tensro attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [45]:
# Create a tensor
some_tensor = torch.rand([3,4], dtype = torch.float32)
some_tensor

tensor([[0.7962, 0.7545, 0.8241, 0.6445],
        [0.3869, 0.7532, 0.2431, 0.5604],
        [0.7002, 0.8686, 0.8592, 0.0058]])

In [46]:
# Find out detail about some_tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7962, 0.7545, 0.8241, 0.6445],
        [0.3869, 0.7532, 0.2431, 0.5604],
        [0.7002, 0.8686, 0.8592, 0.0058]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)-> Fondamentali per fare la convoluzione con i filtri, ad esempio

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [55]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [56]:
# Create a tensor and mult 10 to it
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [57]:
# Create a tensor and sub 10 to it
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [59]:
# Create a tensor and mult 10 to it (PyTorch method)
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication (Convolution)
Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication (scalar or dot product)
2. Matrix multiplication (cross product or
convolution)

In [71]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")


tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [72]:
# Matrix multiplication
torch.matmul(tensor, tensor) # fa (tensor)^T * (tensor)

tensor(14)

In [69]:
a = torch.tensor ([[1,2,3],[4,5,6]])
b = torch.tensor ([[7,8],[9,10],[11,12]])
torch.mm(a,b)


tensor([[ 58,  64],
        [139, 154]])

In [73]:
%%time
value = 0

for i in range (len(tensor)):
  value += tensor [i] * tensor [i]

value

CPU times: user 2.95 ms, sys: 942 µs, total: 3.9 ms
Wall time: 8.16 ms


tensor(14)

In [74]:
%%time
torch.matmul(tensor,tensor) # <-- questo è molto più veloce del for loop

CPU times: user 328 µs, sys: 18 µs, total: 346 µs
Wall time: 351 µs


tensor(14)